version: '3.8'

services:
    user:
        build:
            context: ./userService
        image: microservice/demo/user
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=Microservice-demo-user
        ports:
            - 8080:50051
        depends_on:
            - mongo

    project:
        build:
            context: ./projectService
        image: microservice/demo/project
        restart: "no"
        environment:
            - DB_URI=mysql+mysqldb://root:password@mysql:3306/microservice-project
        ports:
            - 8081:50052
        depends_on:
            - mysql
            - user

    api:
        build:
            context: ./apiService
        image: microservice/demo/api
        restart: "no"
        environment:
            - USER_HOST=user
            - USER_PORT=50051
            - PROJECT_HOST=project
            - PROJECT_PORT=50052
        ports:
            - 8082:50059
        command: serve
        depends_on:
            - user
            - project


    api-gateway:
        image: microservice/demo/api
        restart: "no"
        environment:
            - HOST=api
            - PORT=50059
            - PROXY_PORT=9090
        ports:
            - 9090:9090
        command: proxy
        depends_on:
            - api

    mysql:
        image: mysql:5.7
        restart: "no"
        environment:
            MYSQL_DATABASE: microservice-project
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - mysqldb:/var/lib/mysql

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

volumes:
    mysqldb:
    mongodb:
    mongodb_config: