version: '3.8'

services:
    user:
        build:
            context: ./userService
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=Microservice-demo-user
        ports:
            - 8080:50051
        depends_on:
            - mongo

    project:
        build:
            context: ./projectService
        restart: "no"
        environment:
            - DB_URI=mysql+mysqldb://root:password@mysql:3306/microservice-project
        ports:
            - 8081:50052
        depends_on:
            - mysql
            - user

    mysql:
        image: mysql:5.7
        restart: "no"
        environment:
            MYSQL_DATABASE: microservice-project
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - mysqldb:/var/lib/mysql

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

volumes:
    mysqldb:
    mongodb:
    mongodb_config: